# Generated by Django 2.2.16 on 2020-10-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='manage',
        ),
    ]
